- name: Install Maven
  yum:
    name: maven
    state: present

- name: Download Code
  ansible.builtin.include_role:
    name: common
    tasks_from: download
  vars:
    APP_LOCATION: "/home/roboshop/{{COMPONENT}}"
