- name: Install NodeJS
  ansible.builtin.yum:
    name: [ "nodejs", "make", "gcc-c++" ]
    state: present

- name: Download Code
  ansible.builtin.include_role:
    name: common
    tasks_from: download
  vars:
    APP_LOCATION: "/home/roboshop/{{COMPONENT}}"
    APP_USER: roboshop

- name: Install Nodejs dependencies
  community.general.npm:
    path: /home/roboshop/{{COMPONENT}}
  become_user: roboshop

- name: Update SystemD file
  templet:
    src: systemd.service
    dest: /etc/systemd/system/{{COMPONENT}}.service

- name: start {{COMPONENT}} service
  systemd:
    name: "{{COMPONENYT}}"
    state: restarted
    enabled: yes
    daemon_reload: yes
