help:
    #grep '####' Makefile | grep -v grep | sed -e 's/####//'

cart: #### setup cart component
    #bash component/cart.sh

catalogue: #### setup catalogue component
    #bash component/catalogue.sh

user: #### setup user component
    #bash component/user.sh

shipping: #### setup shipping component
    #bash component/shipping.sh

payment: #### setup payment component
    #bash component/payment.sh

frontend: #### setup frontend component
    #bash component/frontend.sh

mysql: #### setup mysql component
    #bash component/mysql.sh

redis: #### setup redis component
    #bash component/redis.sh

rabitmq: #### setup rabitmq component
    #bash component/rabitmq.sh

mongodb: #### setup mongodb component
    #bash component/mongodb.sh
